# words for hangman game

words = (
    "APPLE", "ORANGE", "STRAWBERRY", "PEAR",  
    "BANANA", "PINEAPPLE", "GRAPE", "MANGO", 
    "BLUEBERRY", "KIWI", "WATERMELON", "PEACH", 
    "CHERRY", "PLUM", "RASPBERRY", "PAPAYA",
    "DOG", "CAT", "ELEPHANT", "GIRAFFE", "TIGER", "LION", "KANGAROO", 
    "PANDA", "ZEBRA", "DOLPHIN",
    "AFRICA", "ASIA", "EUROPE", "AUSTRALIA", "ANTARCTICA",
    "LONDON", "PARIS", "TOKYO", "BERLIN", "SYDNEY", 
    "ROME", "TORONTO", "DUBAI", "ISTANBUL", "BANGKOK", "SINGAPORE", 
    "BARCELONA", "MOSCOW", "CHICAGO", "SEOUL", "MUMBAI",
    "CANADA", "BRAZIL", "GERMANY", "FRANCE", 
    "JAPAN", "AUSTRALIA", "INDIA", "MEXICO", "CHINA",
    "CHAIR", "BOOK", "PHONE", "LAPTOP", "BOTTLE", "GUITAR", 
    "LAMP", "BALL", "SHOES", "CLOCK", "PENCIL",  
    "UMBRELLA", "SCISSORS", "PLATE", 
    "DOOR", "WINDOW", "SOAP", "MIRROR", "BICYCLE", "GLOVES", 
    "FORK", "SPOON", "CAMERA", "WALLET",
    "NOTEBOOK", "COMPUTER", "ELEPHANT", "PAINTING", "SANDWICH", 
    "BROCHURE", "AVOCADOS", "DINOSAUR", "UMBRELLA", "CHOCOLATE",
    "STATION", "CANDLES", "BROTHER", "FORTUNE", "PICTURE", 
    "ORCHARD", "RESPECT", "EXPLORE", "LAUNDRY", "READING")