# words for hangman game

words = (
    "APPLE", "ORANGE", "STRAWBERRY", "PEAR",  
    "BANANA", "PINEAPPLE", "GRAPE", "MANGO",
    "BLUEBERRY", "KIWI", "WATERMELON", "PEACH", 
    "CHERRY", "PLUM", "RASPBERRY", "PAPAYA", "UNIT TESTING",
    "ELEPHANT", "GIRAFFE", "TIGER", "LION", "KANGAROO", 
    "PANDA", "ZEBRA", "DOLPHIN", "NEW ZEALAND",
    "AFRICA", "ASIA", "EUROPE", "AUSTRALIA", "ANTARCTICA",
    "LONDON", "PARIS", "TOKYO", "BERLIN", "SYDNEY", "NEW YORK",
    "ROME", "TORONTO", "DUBAI", "ISTANBUL", "BANGKOK", "SINGAPORE", 
    "BARCELONA", "MOSCOW", "CHICAGO", "SEOUL", "MUMBAI", "SAN FRANCISCO",
    "CANADA", "BRAZIL", "GERMANY", "FRANCE", "ATLANTIC OCEAN", "HONK KONG",
    "JAPAN", "AUSTRALIA", "INDIA", "MEXICO", "CHINA", "LOS ANGELES",
    "CHAIR", "BOOK", "PHONE", "LAPTOP", "BOTTLE", "GUITAR", 
    "LAMP", "BALL", "SHOES", "CLOCK", "PENCIL", "BLACK PANTHER",  
    "UMBRELLA", "SCISSORS", "PLATE", "HARRY POTTER",
    "DOOR", "WINDOW", "SOAP", "MIRROR", "BICYCLE", "GLOVES", 
    "FORK", "SPOON", "CAMERA", "WALLET","JULIA ROBERTS",
    "NOTEBOOK", "COMPUTER", "ELEPHANT", "PAINTING", "SANDWICH", 
    "BROCHURE", "AVOCADOS", "DINOSAUR", "UMBRELLA", "CHOCOLATE",
    "STATION", "CANDLES", "BROTHER", "FORTUNE", "PICTURE", 
    "ORCHARD", "RESPECT", "EXPLORE", "LAUNDRY", "READING")